name: Build and Release Business Card

on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Compile LaTeX
        uses: xu-cheng/latex-action@v2
        with:
          root_file: card.tex

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: card.pdf
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}